### ISSUE TITLE
Python code is actually C++

### ISSUE THREAD

**Issue by ManChicken1911** [PlummersSoftwareLLC/ChatGPTCode#1]
Oops, the Python roman numeral converter from ChatGPT is actually the C++ code :)

**Comment by rbergen** [comment]
@ManChicken1911 You're absolutely right. I missed that when I checked the files before publishing the repo. I'll ask Dave if he can find the actual Python code and put that in the .py file instead.

Good catch, and thanks for reporting it!

**Comment by rbergen** [comment]
it seems Dave is unable to locate the Python code that's missing. I therefore removed the .py file from the repo.

Thanks again for reporting this.

**Comment by davepl** [comment]
I have a movie of the code, I just reailzed I might be able to scrape it, hang on….

OK… fixed!

Cheers,
Dave
